# Generated by Django 2.2.16 on 2022-02-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre_Title',
            new_name='GenreTitle',
        ),
    ]
