# Generated by Django 2.2.16 on 2022-02-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220204_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='Без категории', null=True),
        ),
    ]
