# Generated by Django 2.2.16 on 2022-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220204_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
