# Generated by Django 2.2.16 on 2022-02-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220204_0913'),
        ('reviews', '0006_auto_20220204_2006'),
    ]

    operations = [
    ]
